import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "GPT",
  description: "Generated by 1732",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
